name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install buildozer cython==0.29.33
      - name: Build APK
        env:
          ANDROIDSDK_ACCEPT_LICENSES: 1
        run: buildozer android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: war-apk
          path: bin/*.apk
